config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :localities
  resources :departments
  resources :provinces
  resources :nationalities
  resources :countries
  root to: 'welcome#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/locality.rb
class Locality < ApplicationRecord
  has_paper_trail
  belongs_to :department, required: true
  
end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
  before_action :set_locality, only: %i[ show edit update destroy ]

  # GET /localities or /localities.json
  def index
    @localities = Locality.all
  end

  # GET /localities/1 or /localities/1.json
  def show
  end

  # GET /localities/new
  def new
    @locality = Locality.new
  end

  # GET /localities/1/edit
  def edit
  end

  # POST /localities or /localities.json
  def create
    @locality = Locality.new(locality_params)

    respond_to do |format|
      if @locality.save
        format.html { redirect_to @locality, notice: "Locality was successfully created." }
        format.json { render :show, status: :created, location: @locality }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /localities/1 or /localities/1.json
  def update
    respond_to do |format|
      if @locality.update(locality_params)
        format.html { redirect_to @locality, notice: "Locality was successfully updated." }
        format.json { render :show, status: :ok, location: @locality }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localities/1 or /localities/1.json
  def destroy
    @locality.destroy
    respond_to do |format|
      format.html { redirect_to localities_url, notice: "Locality was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locality
      @locality = Locality.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def locality_params
      params.require(:locality).permit(:name, :national_id, :department_id, :category, :lat, :lon)
    end
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/views/localities/_form.html.erb
<%= form_with(model: locality, local: true) do |form| %>
  <% if locality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(locality.errors.count, "error") %> prohibited this locality from being saved:</h2>

      <ul>
      <% locality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>  
      </ul>
    </div>
  <% end %>
    <div class="mb-3">
      <strong><%= form.label :name, Locality.human_attribute_name("name").titleize, class:"form-label"%></strong>
      <%= form.text_field :name, class:"form-control" %>
    </div>
    <div class="mb-3">
      <strong><%= form.label :national_id, Locality.human_attribute_name("national_id").titleize, class:"form-label"%></strong>
      <%= form.number_field :national_id, class:"form-control" %>
    </div>
    <div class="mb-3">
      <strong><%= form.label :department, Locality.human_attribute_name("department").titleize, class:"form-label"%></strong>
      <%= form.collection_select :department_id, Department.all, :id, :name, {prompt: "Seleccionar"}, {class: "select2 form-control"}  %>
    </div>
    <div class="mb-3">
      <strong><%= form.label :category, Locality.human_attribute_name("category").titleize, class:"form-label"%></strong>
      <%= form.text_field :category, class:"form-control" %>
    </div>
    <div class="mb-3">
      <strong><%= form.label :lat, Locality.human_attribute_name("lat").titleize, class:"form-label"%></strong>
      <%= form.text_field :lat, class:"form-control" %>
    </div>
    <div class="mb-3">
      <strong><%= form.label :lon, Locality.human_attribute_name("lon").titleize, class:"form-label"%></strong>
      <%= form.text_field :lon, class:"form-control" %>
    </div>

  <div class="actions">
    <%= link_to 'Volver', :back, class: "btn btn-primary" %>
    <%= form.submit class: "btn btn-success" %>
<% end %>

app/views/localities/edit.html.erb
<div class="p-2">
  <ol class="breadcrumb mb-0">
    <li class="breadcrumb-item">
      <a href="/">Inicio</a>
    </li>
    <li class="breadcrumb-item">
      <a href="<%= localities_path%>"> <%= Locality.model_name.human(count: 2)%></a>
    </li>
    <li class="breadcrumb-item active">Modificar  <%= Locality.model_name.human%></li>
  </ol>
</div> 

<div class="card card-register mx-auto my-2">
  <div class="card-header">Modificar  <%= Locality.model_name.human%></div>
  <div class="card-body">
    <%= render 'form', locality: @locality %>
    <%= link_to 'Eliminar ' + Locality.model_name.human.titleize, @locality, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar?' }, class: "btn btn-danger"%>
    </div>  
  </div>
</div>

app/views/localities/index.html.erb
<!-- Breadcrumbs-->
<div class="p-2">
  <ol class="breadcrumb mb-0">
    <li class="breadcrumb-item">
      <a href="/">Inicio</a>
    </li>
    <li class="breadcrumb-item active"><a href="<%= localities_path%>"> <%= Locality.model_name.human(count: 2)%></a></li>
  </ol>
</div>
<div class="card mx-auto my-2">
  <div class="card-header">
    <i class="fa fa-table"></i>
    <%= Locality.model_name.human(count: 2).titleize%>
  </div>
  <div class="card-body">
    <table class="datatable responsive nowrap table table-hover">
      <thead>
        <tr>
          <th><%= Locality.human_attribute_name("name").titleize%></th>
          <th><%= Locality.human_attribute_name("national_id").titleize%></th>
          <th><%= Locality.human_attribute_name("department").titleize%></th>
          <th><%= Locality.human_attribute_name("category").titleize%></th>
          <th><%= Locality.human_attribute_name("lat").titleize%></th>
          <th><%= Locality.human_attribute_name("lon").titleize%></th>
          <th>Opciones</th>
        </tr>

      </thead>

      <tbody>
        <% @localities.each do |locality| %>
          <tr>
              <td><%=locality.name%></td>
              <td><%=locality.national_id%></td>
              <td><%=locality.department%></td>
              <td><%=locality.category%></td>
              <td><%=locality.lat%></td>
              <td><%=locality.lon%></td>
            <td>
              <%= link_to((fa_icon "eye"), locality) %>
              <%= link_to((fa_icon "edit"), edit_locality_path(locality)) %>
              <%= link_to((fa_icon "trash"), locality, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar?' }) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>

<div class="actions">
  <%= link_to 'Volver', :back, class: "btn btn-primary" %>
  <%= link_to 'Crear ' + Locality.model_name.human.titleize, new_locality_path, class: 'btn btn-success' %>
</div>
<!-- End Scaffold -->

app/views/localities/new.html.erb
<div class="p-2">
  <ol class="breadcrumb mb-0">
    <li class="breadcrumb-item">
      <a href="/">Inicio</a>
    </li>
    <li class="breadcrumb-item">
      <a href="<%= localities_path%>"> <%= Locality.model_name.human(count: 2)%></a>
    </li>
    <li class="breadcrumb-item active">Crear <%= Locality.model_name.human%></li>
  </ol>
</div> 
<div class="card card-register mx-auto my-2">
  <div class="card-header">Crear <%= Locality.model_name.human%></div>
  <div class="card-body">
    <%= render 'form', locality: @locality %>
    </div>
  </div>
</div>

app/views/localities/show.html.erb
<div class="p-2">
  <ol class="breadcrumb mb-0">
    <li class="breadcrumb-item">
      <a href="/">Inicio</a>
    </li>
    <li class="breadcrumb-item">
      <a href="<%= localities_path%>"> <%= Locality.model_name.human(count: 2)%></a>
    </li>
    <li class="breadcrumb-item active"><%= Locality.model_name.human%></li>
  </ol>
</div> 
<div class="card card-register mx-auto my-2">
  <div class="card-header"><%= @locality.to_s %></div>
  <div class="card-body">
      <p>
        <strong><%= Locality.human_attribute_name("name").titleize%>:</strong>
        <%= @locality.name %>
      </p>
      <p>
        <strong><%= Locality.human_attribute_name("national_id").titleize%>:</strong>
        <%= @locality.national_id %>
      </p>
      <p>
        <strong><%= Locality.human_attribute_name("department").titleize%>:</strong>
        <%= @locality.department %>
      </p>
      <p>
        <strong><%= Locality.human_attribute_name("category").titleize%>:</strong>
        <%= @locality.category %>
      </p>
      <p>
        <strong><%= Locality.human_attribute_name("lat").titleize%>:</strong>
        <%= @locality.lat %>
      </p>
      <p>
        <strong><%= Locality.human_attribute_name("lon").titleize%>:</strong>
        <%= @locality.lon %>
      </p>
    <div class="actions">
      <%= link_to 'Volver', :back, class: "btn btn-primary" %>
      <%= link_to 'Editar Locality', edit_locality_path(@locality), class: 'btn btn-primary' %>
      <%= link_to 'Eliminar ' + Locality.model_name.human.titleize, @locality, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar?' }, class: "btn btn-danger"%>
    </div>
  </div>
</div>