config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :localities
  resources :departments
  resources :provinces
  resources :nationalities
  resources :countries
  root to: 'welcome#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/province.rb
class Province < ApplicationRecord
  has_paper_trail
  belongs_to :country, required: true
  
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  before_action :set_province, only: %i[ show edit update destroy ]

  # GET /provinces or /provinces.json
  def index
    @provinces = Province.all
  end

  # GET /provinces/1 or /provinces/1.json
  def show
  end

  # GET /provinces/new
  def new
    @province = Province.new
  end

  # GET /provinces/1/edit
  def edit
  end

  # POST /provinces or /provinces.json
  def create
    @province = Province.new(province_params)

    respond_to do |format|
      if @province.save
        format.html { redirect_to @province, notice: "Province was successfully created." }
        format.json { render :show, status: :created, location: @province }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provinces/1 or /provinces/1.json
  def update
    respond_to do |format|
      if @province.update(province_params)
        format.html { redirect_to @province, notice: "Province was successfully updated." }
        format.json { render :show, status: :ok, location: @province }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provinces/1 or /provinces/1.json
  def destroy
    @province.destroy
    respond_to do |format|
      format.html { redirect_to provinces_url, notice: "Province was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_province
      @province = Province.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def province_params
      params.require(:province).permit(:iso_id, :name, :national_id, :country_id, :complete_name, :iso_name, :lat, :lon)
    end
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/provinces/_form.html.erb
<%= form_with(model: province, local: true) do |form| %>
  <% if province.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(province.errors.count, "error") %> prohibited this province from being saved:</h2>

      <ul>
      <% province.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>  
      </ul>
    </div>
  <% end %>
    <div class="mb-3">
      <strong><%= form.label :iso_id, Province.human_attribute_name("iso_id").titleize, class:"form-label"%></strong>
      <%= form.text_field :iso_id, class:"form-control" %>
    </div>
    <div class="mb-3">
      <strong><%= form.label :name, Province.human_attribute_name("name").titleize, class:"form-label"%></strong>
      <%= form.text_field :name, class:"form-control" %>
    </div>
    <div class="mb-3">
      <strong><%= form.label :national_id, Province.human_attribute_name("national_id").titleize, class:"form-label"%></strong>
      <%= form.number_field :national_id, class:"form-control" %>
    </div>
    <div class="mb-3">
      <strong><%= form.label :country, Province.human_attribute_name("country").titleize, class:"form-label"%></strong>
      <%= form.collection_select :country_id, Country.all, :id, :name, {prompt: "Seleccionar"}, {class: "select2 form-control"}  %>
    </div>
    <div class="mb-3">
      <strong><%= form.label :complete_name, Province.human_attribute_name("complete_name").titleize, class:"form-label"%></strong>
      <%= form.text_field :complete_name, class:"form-control" %>
    </div>
    <div class="mb-3">
      <strong><%= form.label :iso_name, Province.human_attribute_name("iso_name").titleize, class:"form-label"%></strong>
      <%= form.text_field :iso_name, class:"form-control" %>
    </div>
    <div class="mb-3">
      <strong><%= form.label :lat, Province.human_attribute_name("lat").titleize, class:"form-label"%></strong>
      <%= form.text_field :lat, class:"form-control" %>
    </div>
    <div class="mb-3">
      <strong><%= form.label :lon, Province.human_attribute_name("lon").titleize, class:"form-label"%></strong>
      <%= form.text_field :lon, class:"form-control" %>
    </div>

  <div class="actions">
    <%= link_to 'Volver', :back, class: "btn btn-primary" %>
    <%= form.submit class: "btn btn-success" %>
<% end %>

app/views/provinces/edit.html.erb
<div class="p-2">
  <ol class="breadcrumb mb-0">
    <li class="breadcrumb-item">
      <a href="/">Inicio</a>
    </li>
    <li class="breadcrumb-item">
      <a href="<%= provinces_path%>"> <%= Province.model_name.human(count: 2)%></a>
    </li>
    <li class="breadcrumb-item active">Modificar  <%= Province.model_name.human%></li>
  </ol>
</div> 

<div class="card card-register mx-auto my-2">
  <div class="card-header">Modificar  <%= Province.model_name.human%></div>
  <div class="card-body">
    <%= render 'form', province: @province %>
    <%= link_to 'Eliminar ' + Province.model_name.human.titleize, @province, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar?' }, class: "btn btn-danger"%>
    </div>  
  </div>
</div>

app/views/provinces/index.html.erb
<!-- Breadcrumbs-->
<div class="p-2">
  <ol class="breadcrumb mb-0">
    <li class="breadcrumb-item">
      <a href="/">Inicio</a>
    </li>
    <li class="breadcrumb-item active"><a href="<%= provinces_path%>"> <%= Province.model_name.human(count: 2)%></a></li>
  </ol>
</div>
<div class="card mx-auto my-2">
  <div class="card-header">
    <i class="fa fa-table"></i>
    <%= Province.model_name.human(count: 2).titleize%>
  </div>
  <div class="card-body">
    <table class="datatable responsive nowrap table table-hover">
      <thead>
        <tr>
          <th><%= Province.human_attribute_name("iso_id").titleize%></th>
          <th><%= Province.human_attribute_name("name").titleize%></th>
          <th><%= Province.human_attribute_name("national_id").titleize%></th>
          <th><%= Province.human_attribute_name("country").titleize%></th>
          <th><%= Province.human_attribute_name("complete_name").titleize%></th>
          <th><%= Province.human_attribute_name("iso_name").titleize%></th>
          <th><%= Province.human_attribute_name("lat").titleize%></th>
          <th><%= Province.human_attribute_name("lon").titleize%></th>
          <th>Opciones</th>
        </tr>

      </thead>

      <tbody>
        <% @provinces.each do |province| %>
          <tr>
              <td><%=province.iso_id%></td>
              <td><%=province.name%></td>
              <td><%=province.national_id%></td>
              <td><%=province.country%></td>
              <td><%=province.complete_name%></td>
              <td><%=province.iso_name%></td>
              <td><%=province.lat%></td>
              <td><%=province.lon%></td>
            <td>
              <%= link_to((fa_icon "eye"), province) %>
              <%= link_to((fa_icon "edit"), edit_province_path(province)) %>
              <%= link_to((fa_icon "trash"), province, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar?' }) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>

<div class="actions">
  <%= link_to 'Volver', :back, class: "btn btn-primary" %>
  <%= link_to 'Crear ' + Province.model_name.human.titleize, new_province_path, class: 'btn btn-success' %>
</div>
<!-- End Scaffold -->

app/views/provinces/new.html.erb
<div class="p-2">
  <ol class="breadcrumb mb-0">
    <li class="breadcrumb-item">
      <a href="/">Inicio</a>
    </li>
    <li class="breadcrumb-item">
      <a href="<%= provinces_path%>"> <%= Province.model_name.human(count: 2)%></a>
    </li>
    <li class="breadcrumb-item active">Crear <%= Province.model_name.human%></li>
  </ol>
</div> 
<div class="card card-register mx-auto my-2">
  <div class="card-header">Crear <%= Province.model_name.human%></div>
  <div class="card-body">
    <%= render 'form', province: @province %>
    </div>
  </div>
</div>

app/views/provinces/show.html.erb
<div class="p-2">
  <ol class="breadcrumb mb-0">
    <li class="breadcrumb-item">
      <a href="/">Inicio</a>
    </li>
    <li class="breadcrumb-item">
      <a href="<%= provinces_path%>"> <%= Province.model_name.human(count: 2)%></a>
    </li>
    <li class="breadcrumb-item active"><%= Province.model_name.human%></li>
  </ol>
</div> 
<div class="card card-register mx-auto my-2">
  <div class="card-header"><%= @province.to_s %></div>
  <div class="card-body">
      <p>
        <strong><%= Province.human_attribute_name("iso_id").titleize%>:</strong>
        <%= @province.iso_id %>
      </p>
      <p>
        <strong><%= Province.human_attribute_name("name").titleize%>:</strong>
        <%= @province.name %>
      </p>
      <p>
        <strong><%= Province.human_attribute_name("national_id").titleize%>:</strong>
        <%= @province.national_id %>
      </p>
      <p>
        <strong><%= Province.human_attribute_name("country").titleize%>:</strong>
        <%= @province.country %>
      </p>
      <p>
        <strong><%= Province.human_attribute_name("complete_name").titleize%>:</strong>
        <%= @province.complete_name %>
      </p>
      <p>
        <strong><%= Province.human_attribute_name("iso_name").titleize%>:</strong>
        <%= @province.iso_name %>
      </p>
      <p>
        <strong><%= Province.human_attribute_name("lat").titleize%>:</strong>
        <%= @province.lat %>
      </p>
      <p>
        <strong><%= Province.human_attribute_name("lon").titleize%>:</strong>
        <%= @province.lon %>
      </p>
    <div class="actions">
      <%= link_to 'Volver', :back, class: "btn btn-primary" %>
      <%= link_to 'Editar Province', edit_province_path(@province), class: 'btn btn-primary' %>
      <%= link_to 'Eliminar ' + Province.model_name.human.titleize, @province, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar?' }, class: "btn btn-danger"%>
    </div>
  </div>
</div>