config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :localities
  resources :departments
  resources :provinces
  resources :nationalities
  resources :countries
  root to: 'welcome#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/nationality.rb
class Nationality < ApplicationRecord
  has_paper_trail
  belongs_to :country, required: true
  
end

app/controllers/nationalities_controller.rb
class NationalitiesController < ApplicationController
  before_action :set_nationality, only: %i[ show edit update destroy ]

  # GET /nationalities or /nationalities.json
  def index
    @nationalities = Nationality.all
  end

  # GET /nationalities/1 or /nationalities/1.json
  def show
  end

  # GET /nationalities/new
  def new
    @nationality = Nationality.new
  end

  # GET /nationalities/1/edit
  def edit
  end

  # POST /nationalities or /nationalities.json
  def create
    @nationality = Nationality.new(nationality_params)

    respond_to do |format|
      if @nationality.save
        format.html { redirect_to @nationality, notice: "Nationality was successfully created." }
        format.json { render :show, status: :created, location: @nationality }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @nationality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nationalities/1 or /nationalities/1.json
  def update
    respond_to do |format|
      if @nationality.update(nationality_params)
        format.html { redirect_to @nationality, notice: "Nationality was successfully updated." }
        format.json { render :show, status: :ok, location: @nationality }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @nationality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nationalities/1 or /nationalities/1.json
  def destroy
    @nationality.destroy
    respond_to do |format|
      format.html { redirect_to nationalities_url, notice: "Nationality was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nationality
      @nationality = Nationality.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def nationality_params
      params.require(:nationality).permit(:code, :name, :country_id)
    end
end

app/helpers/nationalities_helper.rb
module NationalitiesHelper
end

app/views/nationalities/_form.html.erb
<%= form_with(model: nationality, local: true) do |form| %>
  <% if nationality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nationality.errors.count, "error") %> prohibited this nationality from being saved:</h2>

      <ul>
      <% nationality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>  
      </ul>
    </div>
  <% end %>
    <div class="mb-3">
      <strong><%= form.label :code, Nationality.human_attribute_name("code").titleize, class:"form-label"%></strong>
      <%= form.text_field :code, class:"form-control" %>
    </div>
    <div class="mb-3">
      <strong><%= form.label :name, Nationality.human_attribute_name("name").titleize, class:"form-label"%></strong>
      <%= form.text_field :name, class:"form-control" %>
    </div>
    <div class="mb-3">
      <strong><%= form.label :country, Nationality.human_attribute_name("country").titleize, class:"form-label"%></strong>
      <%= form.collection_select :country_id, Country.all, :id, :name, {prompt: "Seleccionar"}, {class: "select2 form-control"}  %>
    </div>

  <div class="actions">
    <%= link_to 'Volver', :back, class: "btn btn-primary" %>
    <%= form.submit class: "btn btn-success" %>
<% end %>

app/views/nationalities/edit.html.erb
<div class="p-2">
  <ol class="breadcrumb mb-0">
    <li class="breadcrumb-item">
      <a href="/">Inicio</a>
    </li>
    <li class="breadcrumb-item">
      <a href="<%= nationalities_path%>"> <%= Nationality.model_name.human(count: 2)%></a>
    </li>
    <li class="breadcrumb-item active">Modificar  <%= Nationality.model_name.human%></li>
  </ol>
</div> 

<div class="card card-register mx-auto my-2">
  <div class="card-header">Modificar  <%= Nationality.model_name.human%></div>
  <div class="card-body">
    <%= render 'form', nationality: @nationality %>
    <%= link_to 'Eliminar ' + Nationality.model_name.human.titleize, @nationality, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar?' }, class: "btn btn-danger"%>
    </div>  
  </div>
</div>

app/views/nationalities/index.html.erb
<!-- Breadcrumbs-->
<div class="p-2">
  <ol class="breadcrumb mb-0">
    <li class="breadcrumb-item">
      <a href="/">Inicio</a>
    </li>
    <li class="breadcrumb-item active"><a href="<%= nationalities_path%>"> <%= Nationality.model_name.human(count: 2)%></a></li>
  </ol>
</div>
<div class="card mx-auto my-2">
  <div class="card-header">
    <i class="fa fa-table"></i>
    <%= Nationality.model_name.human(count: 2).titleize%>
  </div>
  <div class="card-body">
    <table class="datatable responsive nowrap table table-hover">
      <thead>
        <tr>
          <th><%= Nationality.human_attribute_name("code").titleize%></th>
          <th><%= Nationality.human_attribute_name("name").titleize%></th>
          <th><%= Nationality.human_attribute_name("country").titleize%></th>
          <th>Opciones</th>
        </tr>

      </thead>

      <tbody>
        <% @nationalities.each do |nationality| %>
          <tr>
              <td><%=nationality.code%></td>
              <td><%=nationality.name%></td>
              <td><%=nationality.country%></td>
            <td>
              <%= link_to((fa_icon "eye"), nationality) %>
              <%= link_to((fa_icon "edit"), edit_nationality_path(nationality)) %>
              <%= link_to((fa_icon "trash"), nationality, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar?' }) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>

<div class="actions">
  <%= link_to 'Volver', :back, class: "btn btn-primary" %>
  <%= link_to 'Crear ' + Nationality.model_name.human.titleize, new_nationality_path, class: 'btn btn-success' %>
</div>
<!-- End Scaffold -->

app/views/nationalities/new.html.erb
<div class="p-2">
  <ol class="breadcrumb mb-0">
    <li class="breadcrumb-item">
      <a href="/">Inicio</a>
    </li>
    <li class="breadcrumb-item">
      <a href="<%= nationalities_path%>"> <%= Nationality.model_name.human(count: 2)%></a>
    </li>
    <li class="breadcrumb-item active">Crear <%= Nationality.model_name.human%></li>
  </ol>
</div> 
<div class="card card-register mx-auto my-2">
  <div class="card-header">Crear <%= Nationality.model_name.human%></div>
  <div class="card-body">
    <%= render 'form', nationality: @nationality %>
    </div>
  </div>
</div>

app/views/nationalities/show.html.erb
<div class="p-2">
  <ol class="breadcrumb mb-0">
    <li class="breadcrumb-item">
      <a href="/">Inicio</a>
    </li>
    <li class="breadcrumb-item">
      <a href="<%= nationalities_path%>"> <%= Nationality.model_name.human(count: 2)%></a>
    </li>
    <li class="breadcrumb-item active"><%= Nationality.model_name.human%></li>
  </ol>
</div> 
<div class="card card-register mx-auto my-2">
  <div class="card-header"><%= @nationality.to_s %></div>
  <div class="card-body">
      <p>
        <strong><%= Nationality.human_attribute_name("code").titleize%>:</strong>
        <%= @nationality.code %>
      </p>
      <p>
        <strong><%= Nationality.human_attribute_name("name").titleize%>:</strong>
        <%= @nationality.name %>
      </p>
      <p>
        <strong><%= Nationality.human_attribute_name("country").titleize%>:</strong>
        <%= @nationality.country %>
      </p>
    <div class="actions">
      <%= link_to 'Volver', :back, class: "btn btn-primary" %>
      <%= link_to 'Editar Nationality', edit_nationality_path(@nationality), class: 'btn btn-primary' %>
      <%= link_to 'Eliminar ' + Nationality.model_name.human.titleize, @nationality, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar?' }, class: "btn btn-danger"%>
    </div>
  </div>
</div>